# EXPOSURE -----------------------------------
quarkus.http.host=127.0.0.1
quarkus.http.port=8087

# DB -----------------------------------------
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/gauge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=update

# AUTH IS HERE -------------------------------
gauge.api-key.access=change-me
gauge.api-key.pepper=change-me
gauge.auth.admin.username=admin
gauge.auth.admin.password=admin
